[package]
name = "mid"
version = "0.1.0"
edition = "2021"
description = "A language built for the twenty-first century"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
